### ISSUE TITLE
`databricks_instance_pool`.`azure_attributes` configuration drift

### ISSUE THREAD

**Issue by moredatapls** [databrickslabs/terraform-provider-databricks#942]
I am using a large number of instances and to speed up deployments I want to be able to set some sort of flag that makes sure that instance pools are not recreated. Currently, whenever I run `terraform apply`, all existing pools are deleted and new pools are created. I noticed that it takes up to 15 minutes until all clusters are up and running again.

This feature would be particularly useful for me during development: I frequently find myself deploying some feature branch to one of our Databricks workspaces to test out some features, and each time I do that I need to wait 5-10 minutes until all instances are recreated.

Is there an option to disable the deletion/creation of instance pools during `terraform apply`?

### Configuration

A subset of the configuration that I use:

```hcl
terraform {
  required_providers {
    databricks = {
      source = "databrickslabs/databricks"
      version = "0.3.11"
    }
  }
}

provider "databricks" {}

data "databricks_spark_version" "latest" {
  latest = true
  scala = "2.12"
  spark_version = "3"
}

resource "databricks_instance_pool" "nodes_d3" {
  instance_pool_name = "D3 2.12 latest"
  min_idle_instances = 0
  max_capacity = 20
  node_type_id = "Standard_D3_v2"

  idle_instance_autotermination_minutes = 15

  preloaded_spark_versions = [
    data.databricks_spark_version.latest.id
  ]

  azure_attributes {
    availability = "SPOT_AZURE"
  }
}

resource "databricks_job" "some_job" {
  name = "Some Spark job"

  new_cluster {
    spark_version = data.databricks_spark_version.latest.id
    instance_pool_id = databricks_instance_pool.nodes_d3.id

    # Single-node config
    spark_conf = {
      "spark.databricks.cluster.profile" = "singleNode"
      "spark.master" = "local[*]"
    }

    custom_tags = {
      "ResourceClass" = "SingleNode"
    }
  }

  # will auto-restart the cluster on update
  always_running = true

  # retry indefinitely
  max_retries = local.max_retries
  min_retry_interval_millis = local.min_retry_interval

  library {
    jar = "/some/path/to/a.jar"
  }

  spark_jar_task {
    main_class_name = "Startup"
  }
}
```

### Expected Behavior

There should be an option to disable the delete/create of the instance pools.

### Actual Behavior

Every time I run `terraform apply` the pools get deleted and recreated.

### Steps to Reproduce

1. use the config above
2. apply: the pools get created
3. apply again: the pools get deleted and re-created

### Terraform and provider versions

- Terraform: 1.0.11
- Databricks provider: 0.3.11

**Comment by nfx** [comment]
@moredatapls which exact fields are forcing new resources? We need to see the diff

**Comment by moredatapls** [comment]
This is an excerpt from the `terraform apply` log, is this what you're looking for?

```
  # databricks_instance_pool.nodes_d13 must be replaced
-/+ resource "databricks_instance_pool" "nodes_d13" {
      ~ id                                    = "1202-084433-nest651-pool-v13ltmsn" -> (known after apply)
      ~ instance_pool_id                      = "1202-084433-nest651-pool-v13ltmsn" -> (known after apply)
        # (7 unchanged attributes hidden)

      ~ azure_attributes {
          - spot_bid_max_price = -1 -> null # forces replacement
            # (1 unchanged attribute hidden)
        }
    }

  # databricks_instance_pool.nodes_d16 must be replaced
-/+ resource "databricks_instance_pool" "nodes_d16" {
      ~ id                                    = "1202-084433-dears649-pool-ju81109z" -> (known after apply)
      ~ instance_pool_id                      = "1202-084433-dears649-pool-ju81109z" -> (known after apply)
        # (7 unchanged attributes hidden)

      ~ azure_attributes {
          - spot_bid_max_price = -1 -> null # forces replacement
            # (1 unchanged attribute hidden)
        }
    }

  # databricks_instance_pool.nodes_d3 must be replaced
-/+ resource "databricks_instance_pool" "nodes_d3" {
      ~ id                                    = "1202-084433-pears650-pool-073gfe07" -> (known after apply)
      ~ instance_pool_id                      = "1202-084433-pears650-pool-073gfe07" -> (known after apply)
        # (7 unchanged attributes hidden)

      ~ azure_attributes {
          - spot_bid_max_price = -1 -> null # forces replacement
            # (1 unchanged attribute hidden)
        }
    }

```

**Comment by alexott** [comment]
I think that we need to mark that field as `computed` - this should fix it

**Comment by moredatapls** [comment]
Oh so I guess this is a bug, not a missing feature

**Comment by nfx** [comment]
@alexott it's more of this annoying DiffSuppressFunc

@moredatapls while we schedule the fix for it, please use lifecycle meta-argument: https://www.terraform.io/docs/language/meta-arguments/lifecycle.html#ignore_changes and add

```hcl
  lifecycle {
    ignore_changes = [azure_attributes] # maybe azure_attributes.spot_bid_max_price will work as well, but not sure
  }
```

**Comment by roy-work** [comment]
I still see drift in `azure_attributes`, even on v0.4.1, which is the version with #981.

Example:
```
      ~ azure_attributes {
          ~ availability       = "SPOT_WITH_FALLBACK_AZURE" -> "ON_DEMAND_AZURE"
          ~ first_on_demand    = 2147483647 -> 1
            # (1 unchanged attribute hidden)
        }
```

**Comment by alexott** [comment]
`SPOT_WITH_FALLBACK_AZURE` isn't supported for instance pools, only spot or on demand - It's [documented](https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/instance_pool#azure_attributes-configuration-block)
