### ISSUE TITLE
[FEATURE] Cluster config validation before sending request

### ISSUE THREAD

**Issue by nfx** [databrickslabs/terraform-provider-databricks#98]
**Is your feature request related to a problem? Please describe.**

Databricks UI provides some validation, so provider has to do it as well. E.g.

```
Error: status 400: err Response from server {"error_code":"INVALID_PARAMETER_VALUE","message":"At least one EBS volume must be attached for clusters created with node type m4.xlarge."}
```

**Describe the solution you'd like**
Cluster config validation before sending request

**Comment by nfx** [comment]
Fixed it with better error handling.

**Comment by Efrat19** [comment]
hey @nfx I get this issue too with 
```
  required_providers {
    databricks = {
      source  = "databrickslabs/databricks"
      version = "0.3.10"
    }
  }
```
when I set the cluster node_type to `m4.xlarge`
What can I do about it?

**Comment by nfx** [comment]
@Efrat19 this is platform error, please follow instructions returned in error message.

**Comment by caldempsey** [comment]
@nfx this is still an issue. there are no helpful instructions on the error message
